version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123

  spring-app:
    image: buihien0109/movie-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db-movie?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123