name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      working-directory: ./movie-app
      run: |
        echo "Maven version:"
        mvn -version
        mvn -B clean install

    - name: Build Docker Image
      working-directory: ./movie-app
      run: docker build -t buihien0109/movie-app:latest .

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Image to Docker Hub
      run: docker push buihien0109/movie-app:latest
